### ISSUE TITLE
Its working fine on windows too...

### ISSUE THREAD

**Issue by SurajKamdiPerficient** [ahmed-musallam/standalone-apache-felix#1]
@ahmed-musallam Its working fine on windows. thanks for making it as a docker image 👍. It was a good idea.

**Comment by ahmed-musallam** [comment]
How do you mean? how did you test? did you run the shell script via WSL?
https://docs.microsoft.com/en-us/windows/wsl/install-win10

or did you use the docker image?

**Comment by SurajKamdiPerficient** [comment]
I used the docker image although we can also use gitbash terminal to run a shell script on windows too.

**Comment by ahmed-musallam** [comment]
sounds good! thanks for reporting that!
